services:
  
  app:
    image: ggau-backend
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
      - liquibase
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ggau_planner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none


  liquibase:
    container_name: pg_updater
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources/changelog:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://db:5432/ggau_planner" --changeLogFile=./changelog/db.changelog-master.xml --username=postgres --password=postgres update
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_DB=ggau_planner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"